name: Laravel Tests

on:
  push:
    branches:
      - master
      - develop

jobs:
  laravel_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.2'

      - name: Run my script
        env:
          CIS: ${{ secrets.CIS }}
        run: |
          # Access the environment variable
          echo $CIS

      - name: Copy .env File
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create SQLite Database
        run: touch database/database.sqlite

      - name: Run Migrations
        run: php artisan migrate --database=sqlite_testing --force

      - name: Cache Configuration
        run: php artisan config:cache

      - name: Run PHPUnit Tests
        run: php artisan test
